### ISSUE TITLE
"check configuration" keeps spinning ?

### ISSUE THREAD

**Issue by SanderM2** [erikkastelec/hass-WEM-Portal#35]
I have a working HA system and I wanted to add this WEM Portal integration.
As soon as I add it to my configuration and I go to "Developer tools" -> "Check configuration", it keeps spinning and never validates or invalidates the configuration.

Anyone else have this issue?

I have it in my configuration.yaml like this:

```
wemportal:
  language: en
  mode: api
  username: xxx@xxx
  password: xxxxx

```
