### ISSUE TITLE
"check configuration" keeps spinning on docker

### ISSUE THREAD

**Issue by Speed1** [erikkastelec/hass-WEM-Portal#44]
Hi,
I have the same issue mentioned in #35
As soon as I add the following lines for the wemportal in my configuration.yaml the "check configuration" keeps spinning. 

```yaml
wemportal:
  username: !secret wemUsername
  password: !secret wemPassword
```

When I restart the container manually in the UI I get "Wrapping up startup, not everything will be available until it is finished" for a while and in the log I get this:
```2022-11-11 19:51:41.385 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration wemportal: Requirements for wemportal not found: ['python-Levenshtein==0.20.*'].```

Do you have some idea how to resolve this?

Best
